export { default as complexInput1 } from './complex_1_input.json'
export { default as complexInput2 } from './complex_2_input.json'
export { default as complexOutput1 } from './complex_1_output.json'
export { default as complexOutput2 } from './complex_2_output.json'
export { default as simpleInput1 } from './simple_1_input.json'
export { default as simpleInput2 } from './simple_2_input.json'
export { default as simpleOutput1 } from './simple_1_output.json'
export { default as simpleOutput2 } from './simple_2_output.json'
